### ISSUE TITLE
Law Widgets Road Map

### ISSUE THREAD

**Issue by musangowope** [laws-africa/law-widgets#164]
- [x] Setup Lerna workspace
- [x] Setup storybook infrastructure
- [x] Package scaffold: `core`(`stencil components`), `react`(`react wrapper package generated from stencil`), `vue`(`vue wrapper` package generated from `stencil`) and Setup infrastructure logic to generate wrapper libraries from core library using [ds-output-target](https://github.com/ionic-team/stencil-ds-output-targets)
- [x] Test vue and react output generation from `core` with **one** existing `la-component`. `la-table-of-contents` is a good straightforward start

- [x] Migrate other existing `la-components`.  In this process, we will improve stories and refactor tests if necessary. List of components:
https://github.com/laws-africa/la-web-components/issues/155

- [x] Update documentation in `README.md`, describing component infrastructure (This is will be iterative process)
- [x] Publish to npm
- [ ] Host our storybook demonstrating all our components to gh pages?
